export const CREATE_THOUGHT = 'CREATE_THOUGHT';

export const SET_SCORE = 'SET_SCORE';

export const SAVE_THOUGHT_REQUEST = 'SAVE_THOUGHT_REQUEST';
export const SAVE_THOUGHT_SUCCESSFUL = 'SAVE_THOUGHT_SUCCESSFUL';
export const SAVE_THOUGHT_FAILED = 'SAVE_THOUGHT_FAILED';

export const SET_THOUGHTS = 'SET_THOUGHTS';
