export const CREATE_THOUGHT_REQUEST = 'CREATE_THOUGHT_REQUEST';
export const CREATE_THOUGHT_SUCCESSFUL = 'CREATE_THOUGHT_SUCCESSFUL';
export const CREATE_THOUGHT_FAILED = 'CREATE_THOUGHT_REQUEST';

export const SAVE_THOUGHT_REQUEST = 'SAVE_THOUGHT_REQUEST';
export const SAVE_THOUGHT_SUCCESSFUL = 'SAVE_THOUGHT_SUCCESSFUL';
export const SAVE_THOUGHT_FAILED = 'SAVE_THOUGHT_FAILED';

export const DELETE_THOUGHT_REQUEST = 'DELETE_THOUGHT_REQUEST';
export const DELETE_THOUGHT_SUCCESSFUL = 'DELETE_THOUGHT_SUCCESSFUL';
export const DELETE_THOUGHT_FAILED = 'DELETE_THOUGHT_FAILED';

export const SET_THOUGHTS = 'SET_THOUGHTS';

export const SET_SCORE = 'SET_SCORE';
