export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const CREATE_THOUGHT = 'CREATE_THOUGHT';

export const SAVE_THOUGHT_REQUEST = 'SAVE_THOUGHT_REQUEST';
export const SAVE_THOUGHT_SUCCESSFUL = 'SAVE_THOUGHT_SUCCESSFUL';
export const SAVE_THOUGHT_FAILED = 'SAVE_THOUGHT_FAILED';

export const DELETE_THOUGHT_REQUEST = 'DELETE_THOUGHT_REQUEST';
export const DELETE_THOUGHT_SUCCESSFUL = 'DELETE_THOUGHT_SUCCESSFUL';
export const DELETE_THOUGHT_FAILED = 'DELETE_THOUGHT_FAILED';

export const CLEAR_THOUGHTS = 'CLEAR_THOUGHTS';

export const SET_USER_THOUGHTS = 'SET_USER_THOUGHTS';

export const SET_SCORE = 'SET_SCORE';
